#!/bin/bash

usage() {
    
}

while getopts "h" opt; do
    case "$opt" in
        h) 
            usage
            echo "Flatten content of files found recursively in the specified directory."
            exit 0
            ;;
        *) usage; exit 1 ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

directory="$1"

if [ ! -d "$directory" ]; then
    echo "Error: '$directory' is not a directory"
    exit 1
fi

export limit_lines

find "$directory" -type f -exec sh -c '
for file; do
    if file -i "$file" | grep -q "text/"; then
        cat "$file"
    fi
done
' sh {} \;